### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by mastricker** [ViktoriiaBaib/curvedataextraction#1]
Hi,
very nice package and thank you for providing it. But before really being able to use it, possibly modify it, I was wondering about the license of this package.

Did you explicitly not provide any details or was this just an oversight?

In any case, I would like to ask if you can add a license so that the usability of the package in various contexts is clear.

Here is a pointer that might help you: [No license?](https://choosealicense.com/no-permission/)

Thanks, best wishes,
Markus

**Comment by ViktoriiaBaib** [comment]
Hi Markus,

Thank you for pointing this out. 
We have added a BSD 3-clause license.

Best,
Viktoriia

**Comment by mastricker** [comment]
Great, thank you!
